--------------------------------------------------------
--  Fichier créé - jeudi-décembre-24-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLOIDETEMPS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."EMPLOIDETEMPS" 
   (	"HEURE" VARCHAR2(20 BYTE), 
	"JOUR" VARCHAR2(20 BYTE), 
	"CODEUE" VARCHAR2(7 BYTE), 
	"IDENS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.EMPLOIDETEMPS
SET DEFINE OFF;
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('07h30-09h30','Lundi','ict201','3');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('09h45-11h45','Lundi','ict213','12');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('11h45-12h00','Lundi','      ','0');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('12h00-14h00','Lundi','ict215','14');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('14h00-14h15','Lundi','      ','0');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('14h15-16h15','Lundi','fra203','2');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('07h30-09h30','Mardi','ict217','16');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('09h30-09h45','Mardi','      ','0');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('09h45-11h45','Mardi','ict203','5');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('11h45-12h00','Mardi','      ','0');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('12h00-14h00','Mardi','ict207','9');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('14h00-14h15','Mardi','      ','0');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('14h15-16h15','Mardi','eng203','1');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('07h30-09h30','Mercredi','ict213','12');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('09h30-09h45','Mercredi','      ','0');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('09h45-11h45','Mercredi','ict205','7');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('11h45-12h00','Mercredi','      ','0');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('12h00-14h00','Mercredi','      ','0');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('14h00-14h15','Mercredi','      ','0');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('14h15-16h15','Mercredi','      ','0');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('07h30-09h30','Jeudi','ict203','5');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('09h30-09h45','Jeudi','      ','0');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('09h45-11h45','Jeudi','ict207','9');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('11h45-12h00','Jeudi','      ','0');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('12h00-14h00','Jeudi','ict217','16');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('14h00-14h15','Jeudi','      ','0');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('14h15-16h15','Jeudi','ict201','3');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('07h30-09h30','Vendredi','ict215','14');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('09h30-09h45','Vendredi','      ','0');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('09h45-11h45','Vendredi','ict205','7');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('11h45-12h00','Vendredi','      ','0');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('12h00-14h00','Vendredi','      ','0');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('14h00-14h15','Vendredi','      ','0');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('14h15-16h15','Vendredi','      ','0');
Insert into SYSTEM.EMPLOIDETEMPS (HEURE,JOUR,CODEUE,IDENS) values ('09h30-09h45','Lundi','      ','0');
--------------------------------------------------------
--  DDL for Index EMPLOIDETEMPS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."EMPLOIDETEMPS_PK" ON "SYSTEM"."EMPLOIDETEMPS" ("HEURE", "JOUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EMPLOIDETEMPS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EMPLOIDETEMPS" ADD CONSTRAINT "EMPLOIDETEMPS_PK" PRIMARY KEY ("HEURE", "JOUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."EMPLOIDETEMPS" MODIFY ("HEURE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOIDETEMPS" MODIFY ("JOUR" NOT NULL ENABLE);
