--------------------------------------------------------
--  Fichier créé - jeudi-décembre-24-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ETUDIANT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ETUDIANT" 
   (	"MATRICULE" VARCHAR2(7 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"SEXE" VARCHAR2(1 BYTE), 
	"DATENAIS" DATE, 
	"LIEUNAIS" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.ETUDIANT
SET DEFINE OFF;
Insert into SYSTEM.ETUDIANT (MATRICULE,NOM,PRENOM,SEXE,DATENAIS,LIEUNAIS) values ('18K2415','ABENA','Eric     ','M',to_date('22/12/20','DD/MM/RR'),'YAOUNDE');
Insert into SYSTEM.ETUDIANT (MATRICULE,NOM,PRENOM,SEXE,DATENAIS,LIEUNAIS) values ('19K2021','BOKOP','Sylvie   ','F',to_date('09/05/01','DD/MM/RR'),'FOUMBAN');
Insert into SYSTEM.ETUDIANT (MATRICULE,NOM,PRENOM,SEXE,DATENAIS,LIEUNAIS) values ('17K1214','DANCHI','Romeo   ','M',to_date('25/09/98','DD/MM/RR'),'BAFANG');
Insert into SYSTEM.ETUDIANT (MATRICULE,NOM,PRENOM,SEXE,DATENAIS,LIEUNAIS) values ('19P2324','EKEN','Stephane  ','M',to_date('11/12/21','DD/MM/RR'),'OBALA');
Insert into SYSTEM.ETUDIANT (MATRICULE,NOM,PRENOM,SEXE,DATENAIS,LIEUNAIS) values ('19M2545','FOUDA','Manuella ','F',to_date('22/12/20','DD/MM/RR'),'MBOUDA');
Insert into SYSTEM.ETUDIANT (MATRICULE,NOM,PRENOM,SEXE,DATENAIS,LIEUNAIS) values ('19N3221','FOUTH','Patricia ','F',to_date('13/08/03','DD/MM/RR'),'BAMENDA');
Insert into SYSTEM.ETUDIANT (MATRICULE,NOM,PRENOM,SEXE,DATENAIS,LIEUNAIS) values ('19O2014','KAMDEM','Yvan    ','M',to_date('16/07/00','DD/MM/RR'),'BAFOUSSAM');
Insert into SYSTEM.ETUDIANT (MATRICULE,NOM,PRENOM,SEXE,DATENAIS,LIEUNAIS) values ('18L2342','MANGA','Livine   ','F',to_date('26/09/20','DD/MM/RR'),'EBOLOWA');
Insert into SYSTEM.ETUDIANT (MATRICULE,NOM,PRENOM,SEXE,DATENAIS,LIEUNAIS) values ('19D5214','TAMO','Roberto   ','M',to_date('29/06/19','DD/MM/RR'),'DSCHANG');
Insert into SYSTEM.ETUDIANT (MATRICULE,NOM,PRENOM,SEXE,DATENAIS,LIEUNAIS) values ('19L2120','WANDJI','Yvane   ','F',to_date('12/07/96','DD/MM/RR'),'BAGANGTE');
--------------------------------------------------------
--  DDL for Index ETUDIANT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ETUDIANT_PK" ON "SYSTEM"."ETUDIANT" ("MATRICULE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ETUDIANT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ETUDIANT" ADD CONSTRAINT "ETUDIANT_PK" PRIMARY KEY ("MATRICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."ETUDIANT" MODIFY ("MATRICULE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."ETUDIANT" MODIFY ("NOM" NOT NULL ENABLE);
