--------------------------------------------------------
--  Fichier créé - jeudi-décembre-24-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MGP
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MGP" 
   (	"MATET" VARCHAR2(7 BYTE), 
	"VALEUR" FLOAT(126)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.MGP
SET DEFINE OFF;
Insert into SYSTEM.MGP (MATET,VALEUR) values ('18K2415','1,8');
Insert into SYSTEM.MGP (MATET,VALEUR) values ('19K2021','1,76');
Insert into SYSTEM.MGP (MATET,VALEUR) values ('17K1214','1,99');
Insert into SYSTEM.MGP (MATET,VALEUR) values ('19P2324','2,35');
Insert into SYSTEM.MGP (MATET,VALEUR) values ('19M2545','2,79');
Insert into SYSTEM.MGP (MATET,VALEUR) values ('19N3221','2,38');
Insert into SYSTEM.MGP (MATET,VALEUR) values ('19O2014','2,71');
Insert into SYSTEM.MGP (MATET,VALEUR) values ('18L2342','2,38');
Insert into SYSTEM.MGP (MATET,VALEUR) values ('19D5214','2,17');
Insert into SYSTEM.MGP (MATET,VALEUR) values ('19L2120','1,69');
--------------------------------------------------------
--  DDL for Index MGP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."MGP_PK" ON "SYSTEM"."MGP" ("MATET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MGP
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MGP" ADD CONSTRAINT "MGP_PK" PRIMARY KEY ("MATET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."MGP" MODIFY ("MATET" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."MGP" MODIFY ("VALEUR" NOT NULL ENABLE);
