--------------------------------------------------------
--  Fichier créé - jeudi-décembre-24-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table QUOTAS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."QUOTAS" 
   (	"VALINF" NUMBER, 
	"VALSUP" NUMBER, 
	"VALFIN" NUMBER, 
	"MENTION" VARCHAR2(2 BYTE), 
	"DECISION" VARCHAR2(5 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.QUOTAS
SET DEFINE OFF;
Insert into SYSTEM.QUOTAS (VALINF,VALSUP,VALFIN,MENTION,DECISION) values ('0','0','0','F ','ECHEC');
Insert into SYSTEM.QUOTAS (VALINF,VALSUP,VALFIN,MENTION,DECISION) values ('0','29,99','0','F ','ECHEC');
Insert into SYSTEM.QUOTAS (VALINF,VALSUP,VALFIN,MENTION,DECISION) values ('30','34,99','0','E ','ECHEC');
Insert into SYSTEM.QUOTAS (VALINF,VALSUP,VALFIN,MENTION,DECISION) values ('35','39,99','1','D ','CANT ');
Insert into SYSTEM.QUOTAS (VALINF,VALSUP,VALFIN,MENTION,DECISION) values ('40','44,99','1,3','D+','CANT ');
Insert into SYSTEM.QUOTAS (VALINF,VALSUP,VALFIN,MENTION,DECISION) values ('45','49,99','1,7','C-','CANT ');
Insert into SYSTEM.QUOTAS (VALINF,VALSUP,VALFIN,MENTION,DECISION) values ('50','54,99','2','C ','CA   ');
Insert into SYSTEM.QUOTAS (VALINF,VALSUP,VALFIN,MENTION,DECISION) values ('55','59,99','2,3','C+','CA   ');
Insert into SYSTEM.QUOTAS (VALINF,VALSUP,VALFIN,MENTION,DECISION) values ('60','64,99','2,7','B-','CA   ');
Insert into SYSTEM.QUOTAS (VALINF,VALSUP,VALFIN,MENTION,DECISION) values ('65','69,99','3','B ','CA   ');
Insert into SYSTEM.QUOTAS (VALINF,VALSUP,VALFIN,MENTION,DECISION) values ('70','74,99','3,3','B+','CA   ');
Insert into SYSTEM.QUOTAS (VALINF,VALSUP,VALFIN,MENTION,DECISION) values ('75','79,99','3,7','A ','CA   ');
Insert into SYSTEM.QUOTAS (VALINF,VALSUP,VALFIN,MENTION,DECISION) values ('80','100','4','A+','CA   ');
--------------------------------------------------------
--  Constraints for Table QUOTAS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."QUOTAS" MODIFY ("VALINF" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."QUOTAS" MODIFY ("VALSUP" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."QUOTAS" MODIFY ("VALFIN" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."QUOTAS" MODIFY ("MENTION" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."QUOTAS" MODIFY ("DECISION" NOT NULL ENABLE);
